apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  #nodeSelector:
    #node.kubernetes.io/instance-type: "m5.xlarge"
  containers:
  - name: pod
    image: ubuntu:20.04
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep 10; done"]
