apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hyperthreading-on
  namespace: kube-system
  labels:
    app.kubernetes.io/name: "hyperthreading-on"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "hyperthreading-on"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "hyperthreading-on"
      name: "hyperthreading-on"
    spec:
      hostPID: true
      hostNetwork: true
      #nodeSelector:
        #beta.kubernetes.io/instance-type: "p4d.24xlarge"
        #processor: gpu
      initContainers:
      - name: "installer"
        image: "ubuntu:20.04"
        #command: ["bash", "-c", "while true; do date; sleep 10; done"]
        command: ["nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--","bash", "-c", "echo on > /sys/devices/system/cpu/smt/control"]
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
      containers:
      - name: "heartbeat"
        image: "ubuntu:20.04"
        command: ["bash", "-c", "while true; do echo Hyperthreading is ON at $(date); sleep 60; done"]

