apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: efa-nccl-test
spec:
  slotsPerWorker: 4
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          initContainers:
          - name: efa-nccl-launcher-init
            image: 159553542841.dkr.ecr.us-west-2.amazonaws.com/cuda-efa-nccl-tests:ubuntu22.04
            command: ["/bin/bash", "-c", "echo waiting for worker pods to start; sleep 5"]
          containers:
          - image: <account>.dkr.ecr.<region>.amazonaws.com/cuda-efa-nccl-tests:ubuntu22.04
            name: efa-nccl-launcher
            env:
             - name: LD_LIBRARY_PATH
               value: /opt/amazon/openmpi/lib:/opt/nccl/build/lib:/opt/amazon/efa/lib:/opt/aws-ofi-nccl/install/lib:/usr/local/nvidia/lib:$LD_LIBRARY_PATH
             - name: PATH
               value: $PATH:/opt/amazon/efa/bin:/usr/bin
             - name: XLA_FLAGS
               value: "--xla_gpu_cuda_data_dir=/usr/local/cuda"
             - name: TF_XLA_FLAGS
               value: "--tf_xla_cpu_global_jit"
             - name: NCCL_DEBUG
               value: INFO
            command:
            - /opt/amazon/openmpi/bin/mpirun
            - --allow-run-as-root
            - --tag-output
            - -np
            - "8"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - PATH
            - -x
            - LD_LIBRARY_PATH
            - -x
            - XLA_FLAGS
            - -x
            - TF_XLA_FLAGS
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_ALGO=RING
            - -x
            - FI_EFA_USE_DEVICE_RDMA=0
            - -x
            - RDMAV_FORK_SAFE=0
            - -x
            - NCCL_DEBUG
            - --mca
            - pml
            - ^cm
            #- --mca
            #- pml_rsh_agent=ssh
            #- --oversubscribe
            - /opt/nccl-tests/build/all_reduce_perf
            - --minbytes
            - "8"
            - --maxbytes
            - 1G
            - --stepfactor
            - "2"
            - --nthreads
            - "1"
            - --ngpus
            - "1"
            - --check
            - "1"
            - --iters
            - "100"
    Worker:
      replicas: 2
      template:
        spec:
          imagePullPolicy: IfNotPresent
          containers:
          - image: <account>.dkr.ecr.<region>.amazonaws.com/cuda-efa-nccl-tests:ubuntu22.04
            name: efa-nccl-worker
            resources:
              limits:
                nvidia.com/gpu: 4
                #hugepages-2Mi: 5120Mi
                vpc.amazonaws.com/efa: 32
                #memory: 8000Mi
              requests:
                nvidia.com/gpu: 4
                #hugepages-2Mi: 5120Mi
                vpc.amazonaws.com/efa: 32
                #memory: 8000Mi
