kind: Deployment
apiVersion: apps/v1
metadata:
  name: gpu-burn
  #namespace: default
  labels:
    app: gpu-burn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpu-burn
  template:
    metadata:
      labels:
        app: gpu-burn
    spec:
      nodeSelector:
        beta.kubernetes.io/instance-type: "p4d.24xlarge"
      containers:
      - name: main
        image: "oguzpastirmaci/gpu-burn"
        imagePullPolicy: IfNotPresent
        #command: ["bash", "-c", "while true; do date; sleep 10; done"]
        command: ["bash", "-c", "while true; do /root/gpu_burn 20; sleep 20; done"]
        resources:
          limits:
            nvidia.com/gpu: 1

