apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-editor-rb
  namespace: ${K8S_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ns-editor
subjects:
- kind: ServiceAccount
  name: ${K8S_NAMESPACE}
  namespace: ${K8S_NAMESPACE}
