apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# This cluster manifest contains a node group with Habana Gaudi DL1 EC2 instances
# To customize this cluster manifest, follow instruction s from:
# https://docs.habana.ai/en/latest/AWS_Quick_Starts/Getting_Started_Guide_EKS/Creating_Cluster_and_Node_Group.html

metadata:
  name: do-eks
  version: "1.21"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  withOIDC: true

managedNodeGroups:

  - name: dl1
    instanceType: dl1.24xlarge
    instancePrefix: dl1
    ami: ami-0e30d8dea91e2d389
    availabilityZones: ["us-east-1a"]
    volumeSize: 500
    minSize: 0
    desiredCapacity: 2
    maxSize: 4
    privateNetworking: true
    efaEnabled: true
    ssh:
      publicKeyName: DL1_Key
    labels: 
      processor: gaudi
    tags:
      k8s.io/cluster-autoscaler/node-template/resources/habana.ai/gaudi: "8"
      k8s.io/cluster-autoscaler/node-template/resources/hugepages-2Mi: "21000Mi"
      k8s.io/cluster-autoscaler/enabled: "true"
    preBootstrapCommands:
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl0/timeout_locked
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl1/timeout_locked
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl2/timeout_locked
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl3/timeout_locked
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl4/timeout_locked
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl5/timeout_locked
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl6/timeout_locked
      - echo 300 | sudo tee /sys/kernel/debug/habanalabs/hl7/timeout_locked
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh do-eks

  - name: g4dn
    instanceType: g4dn.12xlarge
    instancePrefix: g4dn
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: false
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
    labels: { processor: gpu }
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true

