---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-kubeflow
  region: us-west-2
  version: "1.21"
iam:
  withOIDC: true
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 6
  iam:
    withAddonPolicies:
      efs: true
