apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-model-save-map
data:
  S3_BUCKET: s3://YOUR_S3_BUCKET_FOR_MODEL
  MOUNT_PATH: /efs-shared

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-model-save-pod
spec:
  containers:
  - name: efs-model-save-pod
    image: <DOCKER_REGISTRY>eks-s3-copy
    envFrom:
    - configMapRef:
        name: efs-model-save-map
    command: ["/bin/bash"]
    args: ["-c", "/model-save.sh $(S3_BUCKET) $(MOUNT_PATH)"]
    volumeMounts:
    - name: efs-pv
      mountPath: /efs-shared
  volumes:
  - name: efs-pv
    persistentVolumeClaim:
      claimName: efs-pvc
  restartPolicy: Never
