apiVersion: v1
kind: Pod
metadata:
  name: efs-share-test
spec:
  containers:
  - name: efs-share-test
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo  \"hello from EFS\" - $(date -u) >> /efs-shared/test.txt; sleep 120; done"]
    volumeMounts:
    - name: efs-pvc
      mountPath: /efs-shared
  volumes:
  - name: efs-pvc
    persistentVolumeClaim:
      claimName: efs-claim
