apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: hostpath-pv
  resources:
    requests:
      storage: 20Gi
