apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-editor-rb
  namespace: gromacs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ns-editor
subjects:
- kind: ServiceAccount
  name: gromacs
  namespace: gromacs
