apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml-gpu-fsdp
#  name: do-eks-yaml-gpu-g4-p3-p4
  version: "1.25"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.12.6-eksbuild.2

managedNodeGroups:
  - name: p4d-24xlarge-efa
    instanceType: p4d.24xlarge
    instancePrefix: p4d-efa
    privateNetworking: true
#    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 500
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
  - name: p3dn-24xlarge-efa
    instanceType: p3dn.24xlarge
    instancePrefix: p3dn-efa
    privateNetworking: true
#    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 500
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
  - name: g4dn-metal-efa
    instanceType: g4dn.metal
    instancePrefix: g4dn-efa
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 500
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
  - name: g5-2xlarge
    instanceType: g5.2xlarge
    instancePrefix: g5-2xl
    privateNetworking: true
#    availabilityZones: ["us-east-1b"]
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 500
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
  - name: p3-16xlarge
    instanceType: p3.16xlarge
    instancePrefix: p3-16xl
    privateNetworking: true
#    availabilityZones: ["us-east-1b"]
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 500
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
