apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-00122f873b58e3296
    volumeAttributes:
      dnsname: fs-00122f873b58e3296.fsx.us-east-1.amazonaws.com
      mountname: 5ps63bmv
