apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pvc
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: FSx_VOLUME_ID # from AWS FSx console: File system ID
    volumeAttributes:
      dnsname: FSx_DNS_NAME # from AWS FSx console: DNS name
      mountname: FSx_MOUNT_NAME # from AWS FSx console: Mount name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      storage: 1200Gi
